# =====================================================================
# dbt Project Configuration
# ---------------------------------------------------------------------
# File: dbt/dbt_project.yml
# Purpose:
#   Defines your dbt project’s metadata, structure, and default configs.
#   This file tells dbt where to find models, macros, tests, etc.,
#   and how to build them (e.g., materializations, tags, documentation).
#
# Reference:
#   https://docs.getdbt.com/docs/build/projects
# =====================================================================

# ---------------------------------------------------------------------
# 📦 Basic project metadata
# ---------------------------------------------------------------------
name: "stock_market_elt"          # Unique project name (used in manifest + schema naming)
version: "1.0.0"
config-version: 2

# ---------------------------------------------------------------------
# 🔗 Profile configuration
# ---------------------------------------------------------------------
# dbt uses this profile name to find credentials in:
#   ~/.dbt/profiles.yml  (local)
#   or rendered via Airflow in /tmp/dbt_profiles (in DAG runtime)
# The Airflow DAGs in this project dynamically generate it from
# the `snowflake_default` connection stored in AWS Secrets Manager.
profile: "stock_market_elt"

# ---------------------------------------------------------------------
# 🗂️ Project paths (all relative to this dbt/ directory)
# ---------------------------------------------------------------------
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Clean up build artifacts with `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------------------
# 🏗️ Model configurations (by layer)
# ---------------------------------------------------------------------
# dbt lets you organize models into logical layers:
# - staging: raw → clean
# - intermediate: transformations & joins
# - marts: final reporting-ready tables
#
# Each section below defines defaults for models in that folder.
# ---------------------------------------------------------------------
models:
  stock_market_elt:
    # -----------------------------------------------------------------
    # Global defaults (applied to all models in this project)
    # -----------------------------------------------------------------
    +persist_docs:
      relation: true    # Attach doc strings to tables/views
      columns: true     # Attach doc strings to columns

    # -----------------------------------------------------------------
    # 📊 Staging Layer
    # -----------------------------------------------------------------
    # - Cleans and standardizes raw data
    # - Usually views (not tables)
    staging:
      +materialized: view
      # +schema: stg                    # Uncomment for separate schema
      +tags: ["staging"]

    # -----------------------------------------------------------------
    # 🔄 Intermediate Layer
    # -----------------------------------------------------------------
    # - Handles joins, enrichments, and logic between staging + marts
    # - Usually tables (for downstream performance)
    intermediate:
      +materialized: table
      # +schema: int                    # Uncomment for separate schema
      +tags: ["intermediate"]

    # -----------------------------------------------------------------
    # 🏁 Marts Layer (Final)
    # -----------------------------------------------------------------
    # - Business-ready datasets consumed by BI tools or dashboards
    # - Materialized as tables
    marts:
      +materialized: table
      # +schema: marts                  # Uncomment for separate schema
      +tags: ["marts"]
