# dbt/dbt_project.yml

name: "stock_market_elt"
version: "1.0.0"
config-version: 2

# dbt profile name (Cosmos maps this to the Airflow connection)
profile: "stock_market_elt"

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Where to write artifacts (env-overridable for Airflow)
target-path: "{{ env_var('DBT_TARGET_PATH', 'target') }}"
log-path: "{{ env_var('DBT_LOG_PATH', 'logs') }}"

clean-targets:
  - "target"
  - "dbt_packages"

# Snowflake-friendly quoting (avoid unnecessary double quotes)
quoting:
  database: false
  schema: false
  identifier: false

# Persist model & column docs to the warehouse for snapshots & models
# (You can also set this per-folder below.)
models:
  +persist_docs:
    relation: true
    columns: true

snapshots:
  stock_market_elt:
    +persist_docs:
      relation: true
      columns: true
    +tags: ["snapshot"]
    # +schema: snapshots   # uncomment to isolate snapshots to their own schema

# Optional: configure seeds (types, quoting, schema)
# Useful if you add more seeds later or want to enforce types.
seeds:
  stock_market_elt:
    +quote_columns: false
    # +schema: seeds
    # custom_tickers.csv:
    #   +column_types:
    #     ticker: varchar

# Layered model config
models:
  stock_market_elt:
    # Global defaults for all models in the project
    +persist_docs:
      relation: true
      columns: true

    # Staging views; optionally keep in a dedicated schema
    staging:
      +materialized: view
      # +schema: stg
      +tags: ["staging"]

    # Intermediate tables
    intermediate:
      +materialized: table
      # +schema: int
      +tags: ["intermediate"]

    # Marts / final tables
    marts:
      +materialized: table
      # +schema: marts
      +tags: ["marts"]
