# =====================================================================
# dbt Project Configuration
# ---------------------------------------------------------------------
# File: dbt/dbt_project.yml
# =====================================================================

name: "stock_market_elt"
version: "1.0.0"
config-version: 2

# dbt profile name (credentials come from the Airflow-rendered profile
# sourced from the `snowflake_default` secret in AWS Secrets Manager)
profile: "stock_market_elt"

# Project paths (relative to this dbt/ directory)
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# ---------------------------------------------------------------------
# Schema routing + materializations
# ---------------------------------------------------------------------
models:
  stock_market_elt:
    # Global defaults
    +persist_docs:
      relation: true
      columns: true

    # RAW: optional dbt views only (actual landing tables are created by Airflow)
    raw:
      +schema: raw
      +materialized: view
      +tags: ["raw"]

    # PREP: staging + intermediate (incremental by default; set unique_key per model)
    prep:
      +schema: prep
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: append_new_columns
      +tags: ["prep"]

    # MARTS: facts/dims (incremental by default; set unique_key per model)
    marts:
      +schema: marts
      +materialized: incremental
      +incremental_strategy: merge
      +on_schema_change: append_new_columns
      +tags: ["marts"]

# Snapshots: dedicated schema
snapshots:
  stock_market_elt:
    +schema: snapshots

# Seeds: keep reference seeds near transforms
seeds:
  stock_market_elt:
    +schema: prep
