# dbt/dbt_project.yml

name: "stock_market_elt"
version: "1.0.0"
config-version: 2

# dbt profile name (Cosmos maps this to the Airflow connection)
profile: "stock_market_elt"

# Project paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

snapshots:
  stock_market_elt:
    +persist_docs:
      relation: true
      columns: true
    +tags: ["snapshot"]
    # +schema: snapshots   # uncomment to isolate snapshots to their own schema

# Layered model config
models:
  stock_market_elt:
    # Global defaults for all models in the project
    +persist_docs:
      relation: true
      columns: true

    # Staging views; optionally keep in a dedicated schema
    staging:
      +materialized: view
      # +schema: stg
      +tags: ["staging"]

    # Intermediate tables
    intermediate:
      +materialized: table
      # +schema: int
      +tags: ["intermediate"]

    # Marts / final tables
    marts:
      +materialized: table
      # +schema: marts
      +tags: ["marts"]
