# =====================================================================
# Airflow Settings - Pools Configuration
# ---------------------------------------------------------------------
# Purpose:
#   Define task concurrency limits for Airflow DAGs and operators.
#   Pools control how many parallel tasks can run within each category.
#
# Usage:
#   - Place this file in your Astro project root.
#   - Load via: astro dev settings import airflow_settings.yaml
#   - To view pools: astro dev settings list
#
# Reference:
#   https://www.astronomer.io/docs/astro/runtime-configuration#airflow-pools
# =====================================================================

airflow:
  pools:
    # --------------------------------------------------
    # API Pool - limits outbound API concurrency
    # --------------------------------------------------
    # Used by DAGs that make heavy external API calls
    # (e.g., Polygon.io or other rate-limited vendors).
    # Adjust slots based on vendor throughput & API key limits.
    - pool_name: "api_pool"
      pool_slot: 8
      pool_description: "Pool for controlling API-heavy tasks"

    # --------------------------------------------------
    # Default Pool - fallback for all tasks without a pool
    # --------------------------------------------------
    # Do not set this too low; it controls global concurrency.
    - pool_name: "default_pool"
      pool_slot: 128
      pool_description: "Default Airflow pool for general-purpose tasks"
