# =====================================================================
# Airflow Settings - Pools Configuration
# ---------------------------------------------------------------------
# Purpose:
#   Define task concurrency limits for Airflow DAGs and operators.
#   Pools control how many parallel tasks can run within each category.
#
# Usage:
#   - Place this file in your Astro project root.
#   - Load via: astro dev settings import airflow_settings.yaml
#   - To view pools: astro dev settings list
#
# Reference:
#   https://www.astronomer.io/docs/astro/runtime-configuration#airflow-pools
# =====================================================================

airflow:
  pools:
    # --------------------------------------------------
    # API Pool - limits outbound API concurrency
    # --------------------------------------------------
    - pool_name: "api_pool"
      pool_slot: 8
      pool_description: "Pool for controlling API-heavy tasks"

    # --------------------------------------------------
    # LOAD Pool - limits Snowflake COPY concurrency (stream)
    # --------------------------------------------------
    - pool_name: "load_pool"
      pool_slot: 4
      pool_description: "Pool for Snowflake load tasks (stream loaders)"

    # (Optional) Backfill loaders—keep tighter control to avoid WH thrash
    - pool_name: "load_backfill_pool"
      pool_slot: 1
      pool_description: "Pool for Snowflake load tasks (backfill loaders)"

    # --------------------------------------------------
    # Default Pool - fallback for all tasks without a pool
    # --------------------------------------------------
    - pool_name: "default_pool"
      pool_slot: 128
      pool_description: "Default Airflow pool for general-purpose tasks"

    # --------------------------------------------------
    # Snowflake Pool - for Snowflake heavy tasks
    # --------------------------------------------------
    - pool_name: "snowflake_pool"
      pool_slot: 6
      pool_description: "Snowflake COPY/SQL concurrency limit for stocks/options loaders"
