services:
  # One-shot init that renders dbt profiles.yml from AWS SM, then exits
  dbt-init:
    image: ${PROJECT_IMAGE}                # reuse the same image Astro uses
    env_file:
      - .env
    entrypoint: [ "bash", "-lc", "dbt_bootstrap.sh" ]
    restart: "no"
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}/.aws:/home/astro/.aws:ro
      - ./keys:/usr/local/airflow/keys:ro
    environment:
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DBT_PROJECT_DIR=${DBT_PROJECT_DIR}
      - DBT_PROFILE_NAME=${DBT_PROFILE_NAME}
      - SNOWFLAKE_CONN_SECRET_NAME=${SNOWFLAKE_CONN_SECRET_NAME}
      - DBT_BOOTSTRAP_VALIDATE=${DBT_BOOTSTRAP_VALIDATE}
    networks:
      - stocks-elt_default

  scheduler:
    depends_on:
      dbt-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}/.aws:/home/astro/.aws:ro
      - ./keys:/usr/local/airflow/keys:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_CONFIG_FILE=${AWS_CONFIG_FILE}
      - AWS_SHARED_CREDENTIALS_FILE=${AWS_SHARED_CREDENTIALS_FILE}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DBT_PROJECT_DIR=${DBT_PROJECT_DIR}
      - DBT_PROFILE_NAME=${DBT_PROFILE_NAME}
      - SNOWFLAKE_CONN_SECRET_NAME=${SNOWFLAKE_CONN_SECRET_NAME}
    networks:
      - default
      - stocks-elt_default
    restart: unless-stopped

  webserver:
    depends_on:
      dbt-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}/.aws:/home/astro/.aws:ro
      - ./keys:/usr/local/airflow/keys:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_CONFIG_FILE=${AWS_CONFIG_FILE}
      - AWS_SHARED_CREDENTIALS_FILE=${AWS_SHARED_CREDENTIALS_FILE}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DBT_PROJECT_DIR=${DBT_PROJECT_DIR}
      - DBT_PROFILE_NAME=${DBT_PROFILE_NAME}
      - SNOWFLAKE_CONN_SECRET_NAME=${SNOWFLAKE_CONN_SECRET_NAME}
    networks:
      - default
      - stocks-elt_default
    restart: unless-stopped

  triggerer:
    depends_on:
      dbt-init:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}/.aws:/home/astro/.aws:ro
      - ./keys:/usr/local/airflow/keys:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_CONFIG_FILE=${AWS_CONFIG_FILE}
      - AWS_SHARED_CREDENTIALS_FILE=${AWS_SHARED_CREDENTIALS_FILE}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_PROFILES_DIR=${DBT_PROFILES_DIR}
      - DBT_PROJECT_DIR=${DBT_PROJECT_DIR}
      - DBT_PROFILE_NAME=${DBT_PROFILE_NAME}
      - SNOWFLAKE_CONN_SECRET_NAME=${SNOWFLAKE_CONN_SECRET_NAME}
    networks:
      - default
      - stocks-elt_default
    restart: unless-stopped

networks:
  stocks-elt_default:
    name: stocks-elt_default
    driver: bridge
