# customize airflow services
services:
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default
  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default
  triggerer:
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default
# create custom services
  dashboard:
    image: dashboard-app
    container_name: dashboard
    ports:
      - "8501:8501"
    environment:
      # Pass snowflake credentials to the dashboard
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=STOCKS_DASHBOARD_WH # Use the smaller warehouse for the dashboard
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
    networks:
      - stocks-elt_default
networks:
  stocks-elt_default:
    name: stocks-elt_default
    driver: bridge
