# customize airflow services
services:
  scheduler:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default

  webserver:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default

  triggerer:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
    networks:
      - default
      - stocks-elt_default

  # create custom services
  dashboard:
    image: dashboard-app
    container_name: dashboard
    ports:
      - "8501:8501"
    # Mount your local AWS profile so the app can read Secrets Manager
    volumes:
      # Many containers run as root; this path is robust.
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    environment:
      # let the dashboard use the same local profile + region
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # in case the app runs as a non-root user, force AWS SDK to these files
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config

      # tell the app which secret to fetch (Airflow connection URI stored in SM)
      - SNOWFLAKE_CONN_SECRET_NAME=airflow/connections/snowflake_default

      # optional: a smaller WH just for dashboard queries (app should honor this override)
      - SNOWFLAKE_OVERRIDE_WAREHOUSE=STOCKS_DASHBOARD_WH
    networks:
      - stocks-elt_default

networks:
  stocks-elt_default:
    name: stocks-elt_default
    driver: bridge
