# customize airflow services
services:
  scheduler:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${HOME:-${USERPROFILE}}/.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SDK_LOAD_CONFIG=1
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_EXECUTABLE_PATH=/usr/local/airflow/dbt_venv/bin/dbt
      - DBT_THREADS=${DBT_THREADS}
      - DBT_TARGET_PATH=${DBT_TARGET_PATH}
      - HTTP_REQUEST_TIMEOUT_SECS=${HTTP_REQUEST_TIMEOUT_SECS}
      - POLYGON_REQUEST_DELAY_SECONDS=${POLYGON_REQUEST_DELAY_SECONDS}
      - API_POOL=${API_POOL}
    networks:
      - default
      - stocks-elt_default

  webserver:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${HOME:-${USERPROFILE}}/.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SDK_LOAD_CONFIG=1
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_EXECUTABLE_PATH=/usr/local/airflow/dbt_venv/bin/dbt
      - DBT_THREADS=${DBT_THREADS}
      - DBT_TARGET_PATH=${DBT_TARGET_PATH}
      - HTTP_REQUEST_TIMEOUT_SECS=${HTTP_REQUEST_TIMEOUT_SECS}
      - POLYGON_REQUEST_DELAY_SECONDS=${POLYGON_REQUEST_DELAY_SECONDS}
      - API_POOL=${API_POOL}
    networks:
      - default
      - stocks-elt_default

  triggerer:
    env_file:
      - .env
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${HOME:-${USERPROFILE}}/.aws:/home/astro/.aws:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_SDK_LOAD_CONFIG=1
      - AIRFLOW__SECRETS__BACKEND=${AIRFLOW__SECRETS__BACKEND}
      - AIRFLOW__SECRETS__BACKEND_KWARGS=${AIRFLOW__SECRETS__BACKEND_KWARGS}
      - DBT_EXECUTABLE_PATH=/usr/local/airflow/dbt_venv/bin/dbt
      - DBT_THREADS=${DBT_THREADS}
      - DBT_TARGET_PATH=${DBT_TARGET_PATH}
      - HTTP_REQUEST_TIMEOUT_SECS=${HTTP_REQUEST_TIMEOUT_SECS}
      - POLYGON_REQUEST_DELAY_SECONDS=${POLYGON_REQUEST_DELAY_SECONDS}
      - API_POOL=${API_POOL}
    networks:
      - default
      - stocks-elt_default

  # create custom services
  dashboard:
    image: dashboard-app
    container_name: dashboard
    ports:
      - "8501:8501"
    # Mount your local AWS profile so the app can read Secrets Manager
    volumes:
      # Many containers run as root; this path is robust.
      - ${HOME:-${USERPROFILE}}/.aws:/home/astro/.aws:ro
    environment:
      # let the dashboard use the same local profile + region
      - AWS_PROFILE=${AWS_PROFILE}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      # in case the app runs as a non-root user, force AWS SDK to these files
      - AWS_SHARED_CREDENTIALS_FILE=/root/.aws/credentials
      - AWS_CONFIG_FILE=/root/.aws/config

      # tell the app which secret to fetch (Airflow connection URI stored in SM)
      - SNOWFLAKE_CONN_SECRET_NAME=airflow/connections/snowflake_default

      # optional: a smaller WH just for dashboard queries (app should honor this override)
      - SNOWFLAKE_OVERRIDE_WAREHOUSE=STOCKS_DASHBOARD_WH
    networks:
      - stocks-elt_default

networks:
  stocks-elt_default:
    name: stocks-elt_default
    driver: bridge
