# customize airflow services
services:
  webserver:
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    networks:
      - default
      - stocks-elt_default
  scheduler:
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    networks:
      - default
      - stocks-elt_default
  triggerer:
    environment:
      - AWS_PROFILE=default
    volumes:
      - ./dbt:/usr/local/airflow/dbt
      - ${USERPROFILE}\.aws:/home/astro/.aws:ro
    networks:
      - default
      - stocks-elt_default
# create custom services
  dashboard:
    image: dashboard-app
    container_name: dashboard
    ports:
      - "8501:8501"
    environment:
      # Pass snowflake credentials to the dashboard
      - SNOWFLAKE_USER=${SNOWFLAKE_USER}
      - SNOWFLAKE_PASSWORD=${SNOWFLAKE_PASSWORD}
      - SNOWFLAKE_ACCOUNT=${SNOWFLAKE_ACCOUNT}
      - SNOWFLAKE_WAREHOUSE=STOCKS_DASHBOARD_WH # Use the smaller warehouse for the dashboard
      - SNOWFLAKE_DATABASE=${SNOWFLAKE_DATABASE}
      - SNOWFLAKE_SCHEMA=${SNOWFLAKE_SCHEMA}
    networks:
      - stocks-elt_default
networks:
  stocks-elt_default:
    name: stocks-elt_default
    driver: bridge
