-- ====================================================================
-- Snowflake Setup for Stock & Options ELT (Idempotent)
-- ====================================================================
-- AWS S3 Integration:
--   Bucket: s3://stock-market-elt/raw/
--   Region: us-east-2
--   IAM Role: arn:aws:iam::586159464756:role/SnowflakeS3Role
-- ====================================================================

USE ROLE ACCOUNTADMIN;

-- ------------------
-- Warehouses
-- ------------------
CREATE WAREHOUSE IF NOT EXISTS STOCKS_ELT_WH
  WAREHOUSE_SIZE = SMALL
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Primary ELT compute for stocks/options ingestion & transforms';

CREATE WAREHOUSE IF NOT EXISTS STOCKS_DASHBOARD_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND   = 60
  AUTO_RESUME    = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'BI/analytics/dashboard compute';

-- ------------------
-- Database & Schemas
-- ------------------
CREATE DATABASE IF NOT EXISTS STOCKS_ELT_DB COMMENT = 'Dev database for stocks/options ELT';

-- Core schemas
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.PUBLIC     COMMENT = 'Default schema for ELT objects';
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.RAW        COMMENT = 'Raw landed data (immutable as possible)';
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.STAGES     COMMENT = 'Typed landing / staging (pre-model)';
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.PREP       COMMENT = 'Intermediate prep / transforms';
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.MARTS      COMMENT = 'Business-facing marts';
CREATE SCHEMA IF NOT EXISTS STOCKS_ELT_DB.SNAPSHOTS  COMMENT = 'dbt snapshots';

-- ------------------
-- Role
-- ------------------
CREATE ROLE IF NOT EXISTS STOCKS_ELT_ROLE COMMENT = 'Service role for Airflow/dbt running the ELT';

-- ------------------
-- Storage Integration
-- ------------------
CREATE OR REPLACE STORAGE INTEGRATION S3_INTEGRATION
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::586159464756:role/SnowflakeS3Role'
  STORAGE_ALLOWED_LOCATIONS = ('s3://stock-market-elt/raw/')
  COMMENT = 'Integration between Snowflake and S3 for ELT data (scoped to /raw folder)';

-- ------------------
-- File Formats (kept in PUBLIC)
-- ------------------
CREATE OR REPLACE FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE
  COMMENT = 'Default JSON format for Polygon & other API payloads';

CREATE OR REPLACE FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_CSV
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  EMPTY_FIELD_AS_NULL = TRUE
  COMMENT = 'CSV loader (headers in row 1)';

-- ------------------
-- Stage (server-side via storage integration; kept in PUBLIC)
-- ------------------
CREATE OR REPLACE STAGE STOCKS_ELT_DB.PUBLIC.S3_STAGE
  STORAGE_INTEGRATION = S3_INTEGRATION
  URL = 's3://stock-market-elt/raw/'
  FILE_FORMAT = STOCKS_ELT_DB.PUBLIC.FF_JSON
  COMMENT = 'Stage for ELT raw data ingestion (restricted to /raw prefix)';

-- ------------------
-- Privileges
-- ------------------

-- Warehouses for ELT role
GRANT USAGE, OPERATE ON WAREHOUSE STOCKS_ELT_WH       TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE, OPERATE ON WAREHOUSE STOCKS_DASHBOARD_WH TO ROLE STOCKS_ELT_ROLE;
GRANT MONITOR ON WAREHOUSE STOCKS_ELT_WH              TO ROLE STOCKS_ELT_ROLE;
GRANT MONITOR ON WAREHOUSE STOCKS_DASHBOARD_WH        TO ROLE STOCKS_ELT_ROLE;

-- Database
GRANT USAGE         ON DATABASE STOCKS_ELT_DB TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE SCHEMA ON DATABASE STOCKS_ELT_DB TO ROLE STOCKS_ELT_ROLE;

-- Integration & shared helpers in PUBLIC
GRANT USAGE ON INTEGRATION S3_INTEGRATION                 TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON STAGE       STOCKS_ELT_DB.PUBLIC.S3_STAGE  TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_JSON   TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_CSV    TO ROLE STOCKS_ELT_ROLE;

-- ------------------
-- Schema-level grants (mirror PUBLIC across all ELT schemas)
-- ------------------
-- Helper macro (conceptual): apply the same grants to each schema
-- We expand explicitly for clarity and idempotency.

-- List: PUBLIC, RAW, STAGES, PREP, MARTS, SNAPSHOTS
-- Per-schema: USAGE; object creation rights; ALL PRIVILEGES on schema;
-- backfill grants on existing objects; auto-grants on future objects;
-- SYSADMIN read now and future.

-- ========== PUBLIC ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.PUBLIC   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.PUBLIC  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.PUBLIC   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.PUBLIC   TO ROLE SYSADMIN;

-- ========== RAW ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.RAW   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.RAW  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.RAW   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.RAW   TO ROLE SYSADMIN;

-- ========== STAGES ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.STAGES   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.STAGES  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.STAGES   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.STAGES   TO ROLE SYSADMIN;

-- ========== PREP ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.PREP   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.PREP  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.PREP   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.PREP   TO ROLE SYSADMIN;

-- ========== MARTS ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.MARTS   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.MARTS  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.MARTS   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.MARTS   TO ROLE SYSADMIN;

-- ========== SNAPSHOTS ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES       IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT                           ON FUTURE VIEWS        IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE STAGES       IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE                            ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT ON ALL TABLES  IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS  TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS   TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS   TO ROLE SYSADMIN;

-- ------------------
-- Assign Role & user defaults (QoL)
-- ------------------
GRANT ROLE STOCKS_ELT_ROLE TO USER DAVEHASACAT;

ALTER USER DAVEHASACAT
  SET DEFAULT_ROLE      = STOCKS_ELT_ROLE,
      DEFAULT_WAREHOUSE = STOCKS_ELT_WH,
      DEFAULT_NAMESPACE = STOCKS_ELT_DB.PUBLIC;

-- (Optional) Session context for worksheet runs
-- USE ROLE STOCKS_ELT_ROLE;
-- USE WAREHOUSE STOCKS_ELT_WH;
-- USE DATABASE STOCKS_ELT_DB;
-- USE SCHEMA PUBLIC;

-- ====================================================================
-- Done.
-- ====================================================================

DESCRIBE INTEGRATION S3_INTEGRATION;
