-- snowflake/grants.sql
-- Idempotent privilege setup for ELT pipelines

-- === CONFIG (adjust if you rename things) ===
-- Role used by Airflow
SET ROLE_NAME = 'STOCKS_ELT_ROLE';

-- Warehouses
SET WH_INGEST = 'STOCKS_ELT_WH';
SET WH_DASH   = 'STOCKS_DASHBOARD_WH';  -- optional

-- DB/Schema
SET DB_NAME   = 'STOCKS_ELT_DB';
SET SCHEMA_NM = 'PUBLIC';

-- External objects
SET STAGE_NAME     = 's3_stage';         -- STOCKS_ELT_DB.PUBLIC.s3_stage
SET INTEGRATION_NM = 's3_integration';   -- STORAGE INTEGRATION object

-- === GRANTS ===
-- Warehouses
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH_INGEST) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON WAREHOUSE IDENTIFIER($WH_DASH)   TO ROLE IDENTIFIER($ROLE_NAME);

-- Database & Schema usage
GRANT USAGE ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM) TO ROLE IDENTIFIER($ROLE_NAME);

-- Allow creating tables/staging objects in schema (DAGs create tables)
GRANT CREATE TABLE ON SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT CREATE STAGE ON SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM) TO ROLE IDENTIFIER($ROLE_NAME);

-- Storage Integration + Stage
GRANT USAGE ON INTEGRATION IDENTIFIER($INTEGRATION_NM) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON STAGE IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM)||'.'||IDENTIFIER($STAGE_NAME)
  TO ROLE IDENTIFIER($ROLE_NAME);

-- Table-level access (raw source tables & staging tables)
-- Use future grants so new tables created by DAGs are automatically accessible.
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM)
  TO ROLE IDENTIFIER($ROLE_NAME);

-- (Optional) If you anticipate updates/deletes during reconciliation:
-- GRANT UPDATE, DELETE ON FUTURE TABLES IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM)
--   TO ROLE IDENTIFIER($ROLE_NAME);

-- (Optional) If you use FILE FORMATS/SEQUENCES custom objects, add:
-- GRANT USAGE ON FUTURE FILE FORMATS IN SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCHEMA_NM)
--   TO ROLE IDENTIFIER($ROLE_NAME);

-- Verify
SHOW GRANTS TO ROLE IDENTIFIER($ROLE_NAME);
