-- ====================================================================
-- Grants for STOCKS_ELT_ROLE — Database, Schemas, Objects (Idempotent)
-- Mirrors PUBLIC grants to RAW, STAGES, PREP, MARTS, SNAPSHOTS
-- ====================================================================

USE ROLE ACCOUNTADMIN;

-- ------------------
-- Warehouses
-- ------------------
GRANT USAGE, OPERATE, MONITOR
  ON WAREHOUSE STOCKS_ELT_WH       TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE, OPERATE, MONITOR
  ON WAREHOUSE STOCKS_DASHBOARD_WH TO ROLE STOCKS_ELT_ROLE;

-- ------------------
-- Database
-- ------------------
GRANT USAGE
  ON DATABASE STOCKS_ELT_DB TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE SCHEMA
  ON DATABASE STOCKS_ELT_DB TO ROLE STOCKS_ELT_ROLE;

-- ------------------
-- Integration & shared helpers (in PUBLIC)
-- ------------------
GRANT USAGE ON INTEGRATION S3_INTEGRATION                    TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON STAGE       STOCKS_ELT_DB.PUBLIC.S3_STAGE     TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_JSON      TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE ON FILE FORMAT STOCKS_ELT_DB.PUBLIC.FF_CSV       TO ROLE STOCKS_ELT_ROLE;

-- ------------------
-- Schema-level grants (expand per schema)
-- ------------------

-- Helper: apply the same block to each schema in (PUBLIC, RAW, STAGES, PREP, MARTS, SNAPSHOTS)

-- ========== PUBLIC ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

-- Existing objects
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

-- Future objects
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.PUBLIC TO ROLE STOCKS_ELT_ROLE;

-- ========== RAW ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.RAW TO ROLE STOCKS_ELT_ROLE;

-- ========== STAGES ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.STAGES TO ROLE STOCKS_ELT_ROLE;

-- ========== PREP ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.PREP TO ROLE STOCKS_ELT_ROLE;

-- ========== MARTS ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.MARTS TO ROLE STOCKS_ELT_ROLE;

-- ========== SNAPSHOTS ==========
GRANT USAGE ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT,
      CREATE PIPE, CREATE FUNCTION, CREATE PROCEDURE
  ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON ALL VIEWS  IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT SELECT
  ON FUTURE VIEWS IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE STAGES IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;
GRANT USAGE
  ON FUTURE FILE FORMATS IN SCHEMA STOCKS_ELT_DB.SNAPSHOTS TO ROLE STOCKS_ELT_ROLE;

-- (Optional) Reader access for SYSADMIN (comment out if undesired)
GRANT SELECT ON ALL TABLES  IN DATABASE STOCKS_ELT_DB TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE TABLES IN DATABASE STOCKS_ELT_DB TO ROLE SYSADMIN;
GRANT SELECT ON ALL VIEWS   IN DATABASE STOCKS_ELT_DB TO ROLE SYSADMIN;
GRANT SELECT ON FUTURE VIEWS IN DATABASE STOCKS_ELT_DB TO ROLE SYSADMIN;
